version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: logport-postgres
    restart: unless-stopped
    labels:
      - com.logport.monitor=true
    environment:
      POSTGRES_USER: ${LOGPORT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LOGPORT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LOGPORT_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: logport-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - logport-network
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 5

networks:
  logport-network:

volumes:
  pgdata:
  esdata:
