
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: logport-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logport
    ports:
      - "5432:5432"
    networks:
      - logport-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  logport:
    image: logport
    container_name: logport-agent
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logport-network
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
networks:
  logport-network:

volumes:
  pgdata:
